### ISSUE TITLE
Issue 6: Users should be able to like/favourite an entry

### ISSUE THREAD

**Issue by brandon-moy** [brandon-moy/code-journal#12]
`## 💰 Motivation

Users should be able to like/favourite their entries

## 📐 Plan

Create an icon that is clickable to show whether an entry is a favourite or not.

## ✅ Task List

- [x] Add an icon to each entry to denote whether or not something is a favourite.
- [x] Create a new function to check if the icon is the favourite icon or the pencil icon
- [x] For the favourite icon
  - [x] If the entry is not a favourite, change to favourite.
  - [x] If the entry is a favourite is should no longer be a favourite.
- [x] The pencil icon should run the edit code.
- [x] Ensure that the favourite status stays when the page is reloaded.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
