### ISSUE TITLE
Issue 7: Users should be able to view an entire image

### ISSUE THREAD

**Issue by brandon-moy** [brandon-moy/code-journal#14]
## 💰 Motivation

If an image is clipped by the image container, the user should be able to click on the image to expand it. 

## 📐 Plan

Show a hidden modal that takes the target image's src value and displays it.

## ✅ Task List

- [x] Listen for clicks on the images in the entries (or modify existing click listener function)
- [x] Display a modal with an img element in it.
  - [x] The img should take the src from the target image and display it.
  - [x] There should be a way to hide the modal again and close the image.
- [x] The mouse cursor should change when hovering over an image.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
