### ISSUE TITLE
Issue 5: Users should be able to search for an entry

### ISSUE THREAD

**Issue by brandon-moy** [brandon-moy/code-journal#9]
## 💰 Motivation

If a user makes to find a specific entry, they should be able to search for the title of the entry.

## 📐 Plan

Add a search bar that filters out entries to the one the user is searching for.

## ✅ Task List

- [x] Create a search box a user can type their search into.
- [x] Listen for event (keystrokes or input) on the search box.
- [x] Show the entries if their title has matching characters with the text.
- [x] Hide entries if they do not match characters with the text.
- [x] All entries should be visible if the search box is empty / cleared.
- [x] Create a search icon button and hide the search bar.
- [x] Listen for clicks on the search icon button.
- [x] Show the search bar when the search icon is clicks and hide when clicked out of.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
